### ISSUE TITLE
New user input for metric

### ISSUE THREAD

**Issue by micheldumontier** [Nitrogen-DCPPC/FAIRshake#59]
Would like a set of radio boxes, with choices yes, no, maybe:

( ) yes ( ) no  ( ) maybe

**Comment by u8sand** [comment]
Could do that but do you think it's necessary to have `yes no maybe` *and* `yes no but`?

**Comment by micheldumontier** [comment]
no, we just envision the 3 selections, along with justification for any of the decisions, and associated links

**Comment by micheldumontier** [comment]
i think a bigger concern here is how we can provide a wide variety of interface widgets.

**Comment by u8sand** [comment]
I can definitely add `yesnomaybe`. In terms of your other comment, I'm not
sure I fully understand.

**Comment by u8sand** [comment]
So my only concern with this is the fact that the goal of FAIRshake is not
meant as a means to collect this information for all digital objects but to
assess that it can be found by community accepted means.

This is largely because we want to capture what an independent user would
experience in their attempt to utilize a given resource. With semi
automated assessments on their way, I think the simple yes/no is adequate
and, in fact, desirable. Arbitrary expectations about the formatting of any
given answer to that question are part of that evaluation (yes meaning
there and perfectly formatted). Each evaluation is a reset--things could
have been lost since the last assessment, new things could be added.
Collection of FAIR information is already being done by the repositories
which host digital objects, we need not force users to recollect that
information, only to throw it away (we don't have their object to register).

I can add some other widgets if there are cases that warrant it
nonetheless, the only example of which I can think of is code coverage
reporting which is a percentage between good and bad.

Let me know how this sounds and whether or not you agree with this concept.

**Comment by micheldumontier** [comment]
i don't have much experience in formal assessments, so i'm not informed about what is community practice. But I expect that people will want to define both discrete sets (nominals, multinomials) as well as continuous values (ranges, %, etc). so as long as you cover these two spaces, it should be ok.
